### PR TITLE
Update for vs 2019

### PR DESCRIPTION
**Pull request by MBertling**
#25 
Hi @vercellone , 
thanks for sharing this extension! 
I migrated your vsix project to VS2019 and set the version number to 7.0
Unfortunately I was not able to migrate the test projects, because there were some breaking changes in the shell interfaces and because of the change to the AsyncPackage baseclass.
But I think these tests were just initially created by the wizard and did not test the functionality of the autoshelve, so i skipped it.

### CODE REVIEW

**Comment by vercellone** [comment]
@MBertling Thanks for the PR!  It looks like you are on the right path.

If possible, I'd like to make version 7 target (compatible with) Visual Studio 2017, 2019 and beyond.  Be on the lookout for a review requesting changes to that end.

**Review by vercellone — CHANGES_REQUESTED** [review]
**Please make the following changes:**
- In the README and the manifest set the name to "TFS Auto Shelve for Visual Studio" (remove the 2017/2019)
- Remove 2017/2019 from the assembly name in the project properties (i.e. "TfsAutoShelvev7.0").
- Set copyright year to 2019 in Properties/AssemblyInfo.cs
- Set AssemblyVersion and AssemblyFileVersion to 7.0.0.0 in Properties/AssemblyInfo.cs

**Per [Mads Kristensen](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/)**
- Set InstallationTarget Version="[15.0,17.0)"
- Remove the obsolete Microsoft.VisualStudio.MPF.14.0 dependency 
- Set Prerequisite Version="[15.0.25904.2,)"

**appveyor.yml**
- Edit the master branch configuration
  - Change 6.2 to 7.0
  - Change TfsAutoShelve2017v6.2.vsix to TfsAutoShelvev7.0.vsix
  - Change "Visual Studio 2017 RC" to "Visual Studio 2017"

**Optional, but overdue**
- Remove obsolete files
  - EventArgs/WorkSpaceChangedEventArgs.cs
  - IO/OptionsControl.xaml
  - IO/OPtionsControl.xaml.cs
  - IO/OptionsToolWindow.cs
  - Other?

**Comment by MBertling** [comment]
@vercellone unfortunately i could not realize the goal of having a VS2017++ vsix because building the extentsion with VS2017 raised an exception in `VsExt.AutoShelve.TfsAutoShelve.get_TfsExt()` at [TfsAutoShelve.cs line 136](https://github.com/vercellone/tfsautoshelve/blob/master/VsExt.AutoShelve/TfsAutoShelve.cs#L136) when shelving with VS2019. 

So I decided to skip the removal of the 2019 specification or now.

If you have an idea how to solve it, please let me know.

I will proceed with trying to fix the build.

**Review by vercellone — DISMISSED** [review]

**Comment by vercellone** [comment]
@MBertling Good work!  I appreciate the appveyor.yml adjustments to fix the build.

Not sure what the problem is with building in VS 2017, but there is no need.  Building the extension with VS 2019 looks good locally.  Therefore, I've pushed another commit to your branch in order to have appveyor build a 2017+2019 compatible [TFSAutoShelve.7.0.vsix](https://ci.appveyor.com/api/buildjobs/dqr8s4rs874byaws/artifacts/VsExt.AutoShelve%2Fbin%2FPackage%2FTfsAutoShelve.7.0.vsix).  Install that one, and let me know how it goes.

**Comment by MBertling** [comment]
@vercellone Thanks for the update!
To install the package on VS2017 the vsixmanifest must be adapted as you mentioned [before](https://github.com/vercellone/tfsautoshelve/pull/26#pullrequestreview-245627405). 
After that the package could not be loaded. I found the issue in the Activity Log: Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0 is missing.

This can be solved:
- downgrade nuget package Microsoft.VisualStudio.SDK to version 15.9.3
- downgrade nuget package Microsoft.VSSDK.BuildTools to version 15.9.3039
- remove nuget package Microsoft.VisualStudio.SDK.VsixSuppression
- add reference to Microsoft.CSharp

With this modifications the vsix can be compiled, installed and being loaded in both VS versions, but will throw an exception at runtime  at [TfsAutoShelve.cs line 136](https://github.com/vercellone/tfsautoshelve/blob/master/VsExt.AutoShelve/TfsAutoShelve.cs#L136) when shelving with VS2017, because the TeamFoundationServerExt object received from DTE (version 15.0) is not in the appropriate version of the Microsoft.VisualStudio.TeamFoundation.dll (16.0).

I think this could be solved by identifying the VS version at runtime and loading the correct version of the TeamFoundation libraries with reflection, but from my point of view this will go beyond the scope of having a VS2019 version.

Nevertheless the version you created perfectly works for VS2019.

**Comment by vercellone** [comment]
@MBertling Thanks again for this PR!  I've merged it, and followed it up with a PR of my own to get master in sync with the vsix I published to the marketplace last month.  Mine was all guid and vsix manifest changes - no code.

**Pull request merged**
